// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnmdqiywwnoinkstanog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpubWRxaXl3d25vaW5rc3Rhbm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyODY0MjIsImV4cCI6MjA1MDg2MjQyMn0.vi1WFn7-2tXGIJuFuP-Q3NT42p7lqGetnrebj90Etu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);